language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - rbx-head
  - ruby-head
matrix:
  allow_failures:
    - rvm: 1.9.3
    - rvm: rbx-head
    - rvm: ruby-head
notifications:
  webhooks: https://www.buildheroes.com/api/projects/e27637d59452f18b5c97dec76d9b9f4a2e4cfcf4/builds
bundler_args: --without development
before_script:
  - "cp config/database.yml_example config/database.yml"
  - "cp config/initializers/devise.rb_example config/initializers/devise.rb"
script: "bundle exec rake db:drop db:create db:migrate spec"
cache: bundler
