development:
  secret_key_base: '9b6305ce99040fc11e41b03fd915543a57caff83df6b70220e53cb76be79d33514b17cdee8184fdd062c0b94f0db84ad7cccef1e0bd99c32b3c45f0813a7ec7'
  devise_secret_key: '0223fe85fd8a46964e03af1b210492cac3d943814e4f9f2807ad28d742cd8a30bbeea78e398c4402633bcf85366dd115d96a1bd4c83275716c369187ab3d3e3f'
  devise_pepper: 'u2nod2fyemvyifbmzwzmzxjty2h3yxj6zxigugzlzmzlclnjahdhcnplcibq'
  recaptcha_public_key: '6LfiA-cSAAAAAJ3UYspaTW1QR2tqwy9dpr_1abl3'
  recaptcha_private_key: '6LfiA-cSAAAAAB_jAH7L_wxMF4qVMe9n5FSYc_EI'
  auth_twitter_key: ''
  auth_twitter_secret: ''
  twitter_consumer_key: ''
  twitter_consumer_secret: ''
  twitter_access_token: ''
  twitter_access_token_secret: ''

test:
  secret_key_base: '7ce7a3180f54c3b23c99db0e1feccc7da48bd0f49b0c260ddf4818eedc71b41533d97eb67bc35e02207b6fd38ffac75a345519df30b14e11cf04099ec5036b9'
  devise_secret_key: 'f3e3d3ba781963c61757238c4db1a69d511dd66358fcb3362044c893e87aeebb03a8dc247d82da7082f9f4e418349d3cac294012b1fa30e46964a8df58ef3220'
  devise_pepper: 'u2nod2fyemvyifbmzwzmzxjty2h3yxj6zxigugzlzmzlclnjahdhcnplcibq'
  recaptcha_public_key: '6LfiA-cSAAAAAJ3UYspaTW1QR2tqwy9dpr_1abl3'
  recaptcha_private_key: '6LfiA-cSAAAAAB_jAH7L_wxMF4qVMe9n5FSYc_EI'
  auth_twitter_key: ''
  auth_twitter_secret: ''
  twitter_consumer_key: ''
  twitter_consumer_secret: ''
  twitter_access_token: ''
  twitter_access_token_secret: ''

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  recaptcha_public_key: <%= ENV['RECAPTCHA_PUBLIC_KEY'] %>
  recaptcha_private_key: <%= ENV['RECAPTCHA_PRIVATE_KEY'] %>
  auth_twitter_key: <%= ENV['AUTH_TWITTER_KEY'] %>
  auth_twitter_secret: <%= ENV['AUTH_TWITTER_SECRET'] %>
  auth_github_key: <%= ENV['AUTH_GITHUB_KEY'] %>
  auth_github_secret: <%= ENV['AUTH_GITHUB_SECRET'] %>
  twitter_consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
  twitter_consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>
  twitter_access_token: <%= ENV['TWITTER_ACCESS_TOKEN'] %>
  twitter_access_token_secret: <%= ENV['TWITTER_ACCESS_TOKEN_SECRET'] %>
  bugsnag_api_key: <%= ENV['BUGSNAG_API_KEY'] %>
